### ISSUE TITLE
Newline at end of config causes plugin to fail to load

### ISSUE THREAD

**Issue by ajgeiss0702** [LightningReflex/LightningUtils#4]
Some editors add newlines to the end of files by default. I had to check the code to figure out why this plugin was not loading whenever I made a change to the config file.

Even if you won't fix the issue itself, you should probably have a descriptive error message if the last line of the config isn't the `config-version` line.

**Comment by LightningReflex** [comment]
Hey, thanks for the report. Sorry about the long response time.

It should be fixed now :)
